/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Card } from "@mantine/core";

export default function TTTOSPage() {
  return (
    <Card>
      <div className="flex flex-col items-center justify-center">
        <h1 className="mb-4 text-title-36">Terms of Service</h1>
        <div className="text-left text-lg text-body-14">
          <div
            id="tos-welcome-content"
            className="whitespace-pre-wrap p-4 text-body-14"
          >
            <p className="mb-2">
              <strong>Things to Know</strong>
            </p>
            <ul className="ml-5 mt-2">
              <li>
                Stax lets you test, evaluate, and build effective prompts across
                various AI models, including third-party models.
              </li>
              <li>
                You interact with these models via API, using your own API keys.
              </li>
              <li>
                Your use of APIs via Stax remains subject to applicable terms
                and privacy policies, and may incur costs.
              </li>
              <li>
                When you interact with an API via Stax, your data is sent to
                that third party.
              </li>
              <li>
                Google is not responsible for content generated by third-party
                APIs, or for the use of your data by those third parties.
              </li>
            </ul>
            <p className="mb-2">
              <strong>Privacy Notice</strong>
            </p>
            <p>
              The{" "}
              <a href="https://policies.google.com/privacy">
                Google Privacy Policy
              </a>{" "}
              applies to your use of this service.
            </p>
            <p className="mb-2">
              <strong>Trusted Tester Terms</strong>
            </p>
            <p className="mb-2">
              This service is governed by the{" "}
              <a href="https://policies.google.com/terms">
                Google Terms of Service
              </a>
              , which:
            </p>
            <ul className="ml-5 mt-2">
              <li>
                requires you to keep it<strong> confidential</strong>; and
              </li>
              <li>
                grants Google a license to any <strong>feedback</strong> you
                provide.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </Card>
  );
}
