/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import MaterialIcon from "@/components/MaterialIcon";
import AnthropicsAiIcon from "@/components/icons/AnthropicsAiIcon";
import DeepseekAiIcon from "@/components/icons/DeepseekAiIcon";
import GoogleIcon from "@/components/icons/GoogleIcon";
import GrokAiIcon from "@/components/icons/GrokAiIcon";
import MetaIcon from "@/components/icons/MetaIcon";
import MistralAiIcon from "@/components/icons/MistralAiIcon";
import OpenAiIconNew from "@/components/icons/OpenAiIconNew";
import { DatasetUploadFormData, ModelProvider, Provider } from "@/types";
import { SVGProps } from "react";

export const JWT_TOKEN_KEY = "jwtToken";
export const PROJECTS_ONBOARDING_KEY = "projectsOnboarding";
export const UNAUTHORIZED_ERROR_CODE = 403;

export const AUTH_ERROR_TYPES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_VERIFICATION_REQUIRED: "EMAIL_VERIFICATION_REQUIRED",
  PASSWORD_NOT_SET: "PASSWORD NOT SET",
} as const;

export const TOS_PAGE_LINK = "https://support.google.com/legal/answer/15696323";
export const PRIVACY_POLICY = "https://policies.google.com/privacy";
export const REPORT_LEGAL_ISSUE =
  "https://support.google.com/legal/troubleshooter/1114905?sjid=18321866495220854613-NC#ts=1115658%2C13774968";
export const TOS_GOOGLE_LINK = "https://policies.google.com/terms";

export const ERROR_MESSAGES = {
  SESSION_EXPIRED: "Session expired. Please sign in again.",
};

export const getModelDetails = (
  provider: string,
):
  | {
      name: string;
      icon: React.ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
    }
  | undefined => {
  switch (provider) {
    case Provider.GOOGLE:
      return { name: "Google", icon: GoogleIcon };
    case Provider.OPENAI:
      return { name: "OpenAI", icon: OpenAiIconNew };
    case Provider.ANTHROPIC:
      return {
        name: "Claude",
        icon: AnthropicsAiIcon,
      };
    case Provider.MISTRAL:
      return { name: "Mistral", icon: MistralAiIcon };
    case Provider.GROK:
      return {
        icon: GrokAiIcon,
        name: "Grok",
      };
    case Provider.DEEPSEEK:
      return {
        icon: DeepseekAiIcon,
        name: "Deepseek",
      };
    case Provider.LLAMA:
      return {
        icon: MetaIcon,
        name: "Llama",
      };
    // Waiting for the BE to add those two models.
    // case Provider.OLLAMA:
    //   return {
    //     icon: <OllamaAiIcon size={24} />,
    //     name: "Ollama",
    //   };
    // case Provider.HUGGINGFACE:
    //   return {
    //     icon: <HugginFaceAiIcon size={24} />,
    //     name: "HuggingFace",
    //   };
  }
};

export const DEFAULT_EVALUATOR_MODEL = "gemini-flash-latest";

export const getProviders = (): ModelProvider[] => [
  {
    key: "Google",
    accordionName: "Gemini",
    icon: <GoogleIcon size={24} />,
    name: Provider.GOOGLE,
  },
  {
    key: "OpenAI",
    accordionName: "OpenAI",
    icon: <OpenAiIconNew size={24} />,
    name: Provider.OPENAI,
  },
  {
    key: "Anthropic",
    accordionName: "Claude",
    name: Provider.ANTHROPIC,
    icon: <AnthropicsAiIcon size={24} />,
  },
  {
    key: "Mistral",
    accordionName: "Mistral",
    icon: <MistralAiIcon size={24} />,
    name: Provider.MISTRAL,
  },
  {
    key: "Grok",
    accordionName: "Grok",
    icon: <GrokAiIcon size={24} />,
    name: Provider.GROK,
  },
  {
    key: "Deepseek",
    accordionName: "Deepseek",
    icon: <DeepseekAiIcon size={24} />,
    name: Provider.DEEPSEEK,
  },
  {
    key: "Llama",
    accordionName: "Llama",
    icon: <MetaIcon size={24} />,
    name: Provider.LLAMA,
  },
  {
    key: "Custom",
    accordionName: "Custom",
    icon: <MaterialIcon name="developer_mode" size={24} />,
  },
];

export const UPLOAD_DATASET_TOOLTIP_MESSAGES = {
  NO_FILE: "Please upload a file",
  MAX_ROWS_EXCEEDED: (maxRows: number) =>
    `File exceeds the maximum limit of ${maxRows} rows`,
  NAME_REQUIRED: "Dataset name is required",
  INVALID_FORM: "Please fill in all required fields",
};

export const TOOLTIPS = {
  INPUT_COLUMN_HEADER:
    "The user prompt provided to the MODEL to generate OUTPUT.",
  OUTPUT_COLUMN_HEADER:
    'The result generated by the MODEL in response to the INPUT. Use "Generate outputs" to populate.',
  EXPECTED_OUTPUT_COLUMN_HEADER:
    "The ideal or ground truth answer. Use this as the benchmark to evaluate the output.",
  MODEL_COLUMN_HEADER: "The model you want to generate OUTPUTS for.",
  HUMAN_EVALUATION_COLUMN_HEADER: "Provide a human rating for the OUTPUT.",
  LATENCY_COLUMN_HEADER:
    "The time it took the MODEL to generate the OUTPUT after receiving the INPUT.",
  TOKENS_COLUMN_HEADER:
    "The number of tokens in the INPUT and OUTPUT. Token count helps with managing cost, model limits, and prompt optimization.",
  VARIABLES_COLUMN_HEADER:
    "Use this column for any additional data in JSON format. You can reference the JSON keys as variables in INPUTS using {{variable}}",
  TAGS: "Add tags to categorize or filter data.",
  SYSTEM_INSTRUCTION_COLUMN_HEADER:
    "Instructions that defines the AI's persona, rules, and context. This prompt is not shown to end users.",
  PROJECT_METRICS:
    "This section shows aggregated performance and evaluation metrics from your project. Run evaluations on your model's outputs to see more metrics.",
  PROJECT_BENCHMARK:
    "To populate your project benchmark, add your evaluation data, generate model outputs for each input, and run evaluations. For best results, use user prompts from production traffic or known failure cases. While an ideal dataset contains hundreds of examples, starting with even a handful provides valuable insights.",
  CHAT_FORMAT_TOOLTIP:
    "A CSV file where each row represents a complete conversation. The file should include a column for the chat content (in a structured format like JSON) and optionally variables.",
  DATASET_NAME_REQUIRED_MESSAGE: "Dataset name is required",
  NO_ITEMS_SELECTED_MESSAGE: "Select at least one item to perform actions",
  PROJECT_NAME_REQUIRED_MESSAGE: "Project name is required",
  NO_EVALUATORS_SELECTED_MESSAGE:
    "Select at least one evaluator to run evaluation",
  NO_DATASET_SELECTED_MESSAGE: "Select a dataset to import",
  NO_MODEL_SELECTED_MESSAGE: "Select a model to duplicate this row",
  TAG_NAME_REQUIRED_MESSAGE: "Enter a tag name to add",
  CUSTOM_MODEL_VALIDATION_ERROR:
    "Required fields are missing or contain errors (check model name, API URL, and provider selection)",
  CUSTOM_MODEL_NO_CHANGES: "Make changes to enable the update button",
  CONFIRM_DELETE_MESSAGE: "Type 'delete' in the field to confirm deletion",
  EVALUATOR_NAME_REQUIRED: "Evaluator name is required",
  API_KEY_REQUIRED: "Enter an API key to continue",
  ACCEPT_TERMS_REQUIRED: "You must accept the terms to continue",
  NO_EVALUATORS_TO_EXPORT: "No evaluators available to export",
  NO_DATA_TO_SORT: "No evaluators available to sort",
};

export const SAMPLE_DATASET_LINK =
  "https://developers.google.com/stax/datasets#csv_upload";

export enum ApiMappedColumnValue {
  inputColumn = "inputColumn",
  outputColumn = "outputColumn",
  outputColumnA = "outputColumnA",
  outputColumnB = "outputColumnB",
  expectedOutput = "expectedOutput",
  tagsColumn = "tagsColumn",
  systemInstructionColumn = "systemInstructionColumn",
  systemInstructionColumnA = "systemInstructionColumnA",
  systemInstructionColumnB = "systemInstructionColumnB",
  modelLabelColumn = "modelLabelColumn",
  modelLabelColumnA = "modelLabelColumnA",
  modelLabelColumnB = "modelLabelColumnB",
  variablesColumn = "variablesColumn",
  humanEvalScoreColumn = "humanEvalScoreColumn",
  humanEvalScoreNotesColumn = "humanEvalScoreNotesColumn",
  chatColumn = "chatColumn",
  llmEvaluationsColumn = "llmEvaluationsColumn",
  inferenceAnalyticsColumn = "inferenceAnalyticsColumn",
  // SIDE_BY_SIDE
  chatAColumn = "chatAColumn",
  chatBColumn = "chatBColumn",
  llmEvaluationsColumnA = "llmEvaluationsColumnA",
  llmEvaluationsColumnB = "llmEvaluationsColumnB",
  inferenceAnalyticsColumnA = "inferenceAnalyticsColumnA",
  inferenceAnalyticsColumnB = "inferenceAnalyticsColumnB",
}

export type ApiMappedColumnOption = {
  name: string;
  value: ApiMappedColumnValue;
  isRequired?: boolean;
};

export const UPLOAD_COMMON_COLUMNS: ApiMappedColumnOption[] = [
  {
    name: "Expected output",
    value: ApiMappedColumnValue.expectedOutput,
  },
  {
    name: "Tags",
    value: ApiMappedColumnValue.tagsColumn,
  },
  {
    name: "Variables",
    value: ApiMappedColumnValue.variablesColumn,
  },
  {
    name: "Human evaluation",
    value: ApiMappedColumnValue.humanEvalScoreColumn,
  },
  {
    name: "Human evaluation notes",
    value: ApiMappedColumnValue.humanEvalScoreNotesColumn,
  },
];

export const UPLOAD_POINTWISE_COLUMNS: ApiMappedColumnOption[] = [
  {
    name: "Input",
    value: ApiMappedColumnValue.inputColumn,
    isRequired: true,
  },
  {
    name: "Output",
    value: ApiMappedColumnValue.outputColumn,
  },
  {
    name: "System Instructions",
    value: ApiMappedColumnValue.systemInstructionColumn,
  },
  {
    name: "Model Nickname",
    value: ApiMappedColumnValue.modelLabelColumn,
  },
  ...UPLOAD_COMMON_COLUMNS,
  {
    name: "LLM Evaluations",
    value: ApiMappedColumnValue.llmEvaluationsColumn,
  },
  {
    name: "Inference Analytics",
    value: ApiMappedColumnValue.inferenceAnalyticsColumn,
  },
];

export const UPLOAD_CHAT_FORMAT_COLUMNS: ApiMappedColumnOption[] = [
  {
    name: "Chat",
    value: ApiMappedColumnValue.chatColumn,
    isRequired: true,
  },
  {
    name: "Variables",
    value: ApiMappedColumnValue.variablesColumn,
  },
];

export const UPLOAD_SXS_COLUMNS: ApiMappedColumnOption[] = [
  {
    name: "Input",
    value: ApiMappedColumnValue.inputColumn,
    isRequired: true,
  },
  {
    name: "Output A",
    value: ApiMappedColumnValue.outputColumnA,
  },
  {
    name: "Output B",
    value: ApiMappedColumnValue.outputColumnB,
  },
  {
    name: "System Instructions A",
    value: ApiMappedColumnValue.systemInstructionColumnA,
  },
  {
    name: "System Instructions B",
    value: ApiMappedColumnValue.systemInstructionColumnB,
  },
  {
    name: "Model Nickname A",
    value: ApiMappedColumnValue.modelLabelColumnA,
  },
  {
    name: "Model Nickname B",
    value: ApiMappedColumnValue.modelLabelColumnB,
  },
  {
    name: "LLM Evaluations A",
    value: ApiMappedColumnValue.llmEvaluationsColumnA,
  },
  {
    name: "LLM Evaluations B",
    value: ApiMappedColumnValue.llmEvaluationsColumnB,
  },
  {
    name: "Inference Analytics A",
    value: ApiMappedColumnValue.inferenceAnalyticsColumnA,
  },
  {
    name: "Inference Analytics B",
    value: ApiMappedColumnValue.inferenceAnalyticsColumnB,
  },
  ...UPLOAD_COMMON_COLUMNS,
];

export const UPLOAD_SXS_CHAT_FORMAT_COLUMNS: ApiMappedColumnOption[] = [
  {
    name: "Chat A",
    value: ApiMappedColumnValue.chatAColumn,
    isRequired: true,
  },
  {
    name: "Chat B",
    value: ApiMappedColumnValue.chatBColumn,
  },
  {
    name: "Variables",
    value: ApiMappedColumnValue.variablesColumn,
  },
];

export const UPLOAD_DATASET_INITIAL_VALUES: DatasetUploadFormData = {
  file: null,
  name: "",
  description: "",
  inputColumn: "",
  outputColumn: "",
  expectedOutput: "",
  tagsColumn: "",
  systemInstructionColumn: "",
  modelLabelColumn: "",
  variablesColumn: "",
  humanEvalScoreColumn: "",
  humanEvalScoreNotesColumn: "",
  chatColumn: "",
  llmEvaluationsColumn: "",
  inferenceAnalyticsColumn: "",
  // SIDE_BY_SIDE fields
  chatAColumn: "",
  chatBColumn: "",
  outputColumnA: "",
  outputColumnB: "",
  systemInstructionColumnA: "",
  systemInstructionColumnB: "",
  modelLabelColumnA: "",
  modelLabelColumnB: "",
  llmEvaluationsColumnA: "",
  llmEvaluationsColumnB: "",
  inferenceAnalyticsColumnA: "",
  inferenceAnalyticsColumnB: "",
};

export const LOCAL_STORAGE_LOGINS_LIST_KEY = "userLogins";
export const LOCAL_STORAGE_AUTO_SURVEY_SHOWN_KEY = "autoSurveyShown";
export const LOCAL_STORAGE_AUTO_SURVEY_MINIMUM_LOGIN_COUNT = 3;
export const LOCAL_STORAGE_AUTO_SURVEY_MAXIMUM_LOGIN_DAY_SPAN = 30;
export const LOCAL_STORAGE_KEYS_TO_PRESERVE_ON_CLEAR = [
  LOCAL_STORAGE_LOGINS_LIST_KEY,
  LOCAL_STORAGE_AUTO_SURVEY_SHOWN_KEY,
];
export const LOCAL_STORAGE_SHOW_CUSTOM_MODEL_MODAL = "showCustomModal";
export const PLAYGROUND_CUSTOM_INPUT_NAME = "custom-input";
