/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  EvaluationStatusColor,
  LLMEvaluatorOutputCategory,
  ProjectType,
} from "@/types";

export const promptHelperText = {
  [ProjectType.POINTWISE]:
    "Craft a clear set of instructions for the AI model. This prompt will guide the model in assessing a generated output on criteria you define, and then assign a specific score based on this criteria. Your instructions can use {{output}} for the model's last generated response and can optionally use {{input}} for the original user prompt, {{history}} for chat history, {{expected_output}} for the ground truth and {{system.instruction}} for the respective system instructions. These variables will be replaced with actual data from your dataset during evaluation.",
  [ProjectType.SIDE_BY_SIDE]:
    "Craft a clear set of instructions for the AI model. This prompt will guide the model in assessing a generated output on criteria you define, and then assign a specific score based on this criteria. Your instructions can use {{output.A}} and {{output.B}} for the model's last generated response of the respective side of the pair. It can optionally use {{input}} ({{input.A}} and {{input.B}} are also available, though the inputs always match) for the original user prompt, {{history.A}} and {{history.B}} for chat history, {{expected_output}} for the ground truth and {{system.instruction.A}} {{system.instruction.B}} for the respective system instructions. These variables will be replaced with actual data from your dataset during evaluation.",
};

export const promptDefaultText = `# Instruction
You are an expert evaluator. Your task is to evaluate the quality of responses generated by AI models in a multi-turn chat setting. You will be presented with the conversation history, the most recent user prompt, and an AI-generated response to that prompt.
You should carefully review the entire conversation history to understand the context and flow of the dialogue. Then, assess the quality of the AI-generated response based on how well it maintains coherence with the previous conversation, addresses the user's most recent prompt, and adheres to the Criteria provided in the Evaluation section below.
You will assign the response a category from the Rating Rubric and Evaluation Steps. Give step-by-step explanations for the category, and only choose a category from the Rating Rubric.
 
# Evaluation
## Metric Definition
You will be assessing Multi-turn Chat Quality, which measures how effectively the AI-generated response contributes to a meaningful, coherent, and engaging conversation, considering factors like context fluency, groundedness, and conciseness.
 
## Criteria Definition
Coherence: The response presents ideas in a logical and organized manner, with clear transitions and a consistent focus, making it easy to follow and understand.
Fluency: The text flows smoothly and naturally, adhering to grammatical rules and using appropriate vocabulary.
Instruction following: The response demonstrates a clear understanding of the task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context. The response does not reference any outside information.
Verbosity: The response is appropriately concise, providing sufficient detail without using complex language to thoroughly address the prompt without being overly wordy or excessively brief.
Collaborativity: The response actively contributes to the conversation by asking relevant follow-up questions, making suggestions, or offering insights when appropriate.
Recall: The response demonstrates a clear understanding of the previous conversation, referencing and utilizing relevant information from earlier turns.
 
## Rating Rubric
Very good: Exceptionally collaborative, demonstrating excellent recall, appropriate verbosity, and strong adherence to instructions. Fully grounded in the conversation context.
Good: Collaborative, with good recall, appropriate verbosity, and mostly adheres to instructions. Mostly grounded in the conversation context, with minor inconsistencies.
Ok: Somewhat collaborative, demonstrating adequate recall and verbosity. Partially fulfills instructions and may contain minor ungrounded information.
Bad: Lacks collaborativity, struggles with recall and verbosity. Fails to adhere to instructions and may include significant ungrounded information.
Very bad: Non-collaborative, demonstrates poor recall and verbosity. Completely disregards instructions and contains substantial ungrounded information.
 
## Evaluation Steps
STEP 1: Carefully review the entire conversation history to gain a comprehensive understanding of the context and flow of the dialogue.
STEP 2: Assess the response in aspects of all criteria provided . Provide assessment according to each criterion.
STEP 3: Assign a category based on the Rating Rubric. Give a brief rationale to explain your evaluation considering each individual criterion and the overall contribution to the conversation.
 
# Response Output
Your response must strictly follow this two line format: the first line must be the category and the second line must be the reasoning.
 
Here is an example format of the output:
Bad 
The response is a Bad because it fails to follow instructions by providing only one of the two requested coffee shops and is not grounded because it introduced external information, describing Stumptown as "world-famous" and Forest Park as "popular with tourists."
 
# User Inputs and AI-generated Response
## User Inputs
 
### Conversation History
{{history}}
 
### Current User Prompt
{{input}}
 
## AI-generated Response
{{output}}`;

export const promptDefaultTextSxS = `# Instruction 
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B). You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below. You will first judge responses individually, following the Rating Rubric and Evaluation Steps. Then you will give step-by-step explanations for your judgment, compare results to declare the winner based on the Rating Rubric and Evaluation Steps. 

# Evaluation
## Metric Definition
You will be assessing fluency, which measures language mastery of the model's response based on the user prompt.

## Criteria
Fluency: The text is free of grammatical errors, employs varied sentence structures, and maintains a consistent tone and style, resulting in a smooth and natural flow that is easy to understand.

## Rating Rubric
"A": Response A is better than Response B based on the Fluency criteria provided. It demonstrates superior grammar, nuanced word choice, and a natural, seamless flow compared to Response B.
"SAME": Response A and B are of the same quality based on the Fluency criteria provided. They exhibit comparable levels of grammar accuracy, word choice sophistication, and natural flow.
"B": Response B is better than Response A based on the Fluency criteria provided. It demonstrates superior grammar, nuanced word choice, and a natural, seamless flow compared to Response A.

## Evaluation Steps
STEP 1: Analyze Response A based on the Fluency Criteria.
STEP 2: Analyze Response B based on the Fluency Criteria.
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment.
STEP 4: Output your preference of "A", "SAME" or "B" to the pairwise_choice field according to the Rating Rubric.
STEP 5: Output your assessment reasoning in the explanation field.

# User Inputs and AI-generated Responses
## User Inputs
### Prompt
{prompt}

## AI-generated Responses 

### Response A
{baseline_model_response}

### Response B
{response}`;
export const defaultOutputCategories: LLMEvaluatorOutputCategory[] = [
  {
    name: "Excellent",
    value: "1.0",
    color: EvaluationStatusColor.GREEN,
    color_name: "Green",
  },
  {
    name: "Ok",
    value: "0.5",
    color: EvaluationStatusColor.ORANGE,
    color_name: "Orange",
  },
  {
    name: "Bad",
    value: "0.0",
    color: EvaluationStatusColor.RED,
    color_name: "Red",
  },
];

export const defaultSxSOutputCategories: LLMEvaluatorOutputCategory[] = [
  {
    name: "A",
    color: EvaluationStatusColor.GREEN,
    color_name: "Green",
    value: "A",
  },
  {
    name: "TIE",
    color: EvaluationStatusColor.BLUE,
    color_name: "Blue",
    value: "TIE",
  },
  {
    name: "B",
    color: EvaluationStatusColor.GREEN,
    color_name: "Green",
    value: "B",
  },
];
