FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /workspace/app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src src

RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /workspace/app/target/*.war app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.war"]