/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  defaultOutputCategories,
  promptDefaultText,
} from "@/app/(authRoutes)/evaluatorGallery/[id]/config/Constants";
import { EvaluationStatusColor } from "@/types";

describe("Constants", () => {
  describe("promptDefaultText", () => {
    it("should be a string", () => {
      expect(typeof promptDefaultText).toBe("string");
    });

    it("should contain the expected instruction structure", () => {
      expect(promptDefaultText).toContain("# Instruction");
      expect(promptDefaultText).toContain("You are an expert evaluator");
      expect(promptDefaultText).toContain(
        "evaluate the quality of responses generated by AI models",
      );
    });

    it("should contain the evaluation section", () => {
      expect(promptDefaultText).toContain("# Evaluation");
      expect(promptDefaultText).toContain("## Metric Definition");
      expect(promptDefaultText).toContain("## Criteria");
      expect(promptDefaultText).toContain("## Rating Rubric");
      expect(promptDefaultText).toContain("## Evaluation Steps");
    });

    it("should contain the response output section", () => {
      expect(promptDefaultText).toContain("# Response Output");
      expect(promptDefaultText).toContain(
        "Your response must strictly follow this two line format",
      );
    });

    it("should contain the user inputs section", () => {
      expect(promptDefaultText).toContain(
        "# User Inputs and AI-generated Response",
      );
      expect(promptDefaultText).toContain("## User Inputs");
      expect(promptDefaultText).toContain("### Conversation History");
      expect(promptDefaultText).toContain("### Current User Prompt");
      expect(promptDefaultText).toContain("## AI-generated Response");
    });

    it("should contain template variables", () => {
      expect(promptDefaultText).toContain("{{history}}");
      expect(promptDefaultText).toContain("{{input}}");
      expect(promptDefaultText).toContain("{{output}}");
    });

    it("should contain evaluation criteria", () => {
      expect(promptDefaultText).toContain("Instruction following");
      expect(promptDefaultText).toContain("Groundedness");
      expect(promptDefaultText).toContain("Verbosity");
      expect(promptDefaultText).toContain("Fluency");
      expect(promptDefaultText).toContain("Coherence");
    });

    it("should contain rating rubric categories", () => {
      expect(promptDefaultText).toContain("Very good:");
      expect(promptDefaultText).toContain("Ok:");
      expect(promptDefaultText).toContain("Bad:");
    });

    it("should contain evaluation steps", () => {
      expect(promptDefaultText).toContain("STEP 1:");
      expect(promptDefaultText).toContain("STEP 2:");
    });

    it("should contain example output format", () => {
      expect(promptDefaultText).toContain(
        "Here is an example format of the output:",
      );
      expect(promptDefaultText).toContain("Bad");
      expect(promptDefaultText).toContain("The response is a Bad because");
    });
  });

  describe("defaultOutputCategories", () => {
    it("should be an array", () => {
      expect(Array.isArray(defaultOutputCategories)).toBe(true);
    });

    it("should have exactly 3 categories", () => {
      expect(defaultOutputCategories).toHaveLength(3);
    });

    it("should contain Excellent category", () => {
      const excellentCategory = defaultOutputCategories.find(
        (cat) => cat.name === "Excellent",
      );
      expect(excellentCategory).toBeDefined();
      expect(excellentCategory).toEqual({
        name: "Excellent",
        value: "1.0",
        color: EvaluationStatusColor.GREEN,
        color_name: "Green",
      });
    });

    it("should contain Ok category", () => {
      const okCategory = defaultOutputCategories.find(
        (cat) => cat.name === "Ok",
      );
      expect(okCategory).toBeDefined();
      expect(okCategory).toEqual({
        name: "Ok",
        value: "0.5",
        color: "var(--color-orange)",
        color_name: "Orange",
      });
    });

    it("should contain Bad category", () => {
      const badCategory = defaultOutputCategories.find(
        (cat) => cat.name === "Bad",
      );
      expect(badCategory).toBeDefined();
      expect(badCategory).toEqual({
        name: "Bad",
        value: "0.0",
        color: EvaluationStatusColor.RED,
        color_name: "Red",
      });
    });

    it("should have unique names for each category", () => {
      const names = defaultOutputCategories.map((cat) => cat.name);
      const uniqueNames = new Set(names);
      expect(uniqueNames.size).toBe(names.length);
    });

    it("should have unique values for each category", () => {
      const values = defaultOutputCategories.map((cat) => cat.value);
      const uniqueValues = new Set(values);
      expect(uniqueValues.size).toBe(values.length);
    });

    it("should have valid LLMEvaluatorOutputCategory structure for each item", () => {
      defaultOutputCategories.forEach((category) => {
        expect(category).toHaveProperty("name");
        expect(category).toHaveProperty("value");
        expect(category).toHaveProperty("color");
        expect(category).toHaveProperty("color_name");

        expect(typeof category.name).toBe("string");
        expect(typeof category.value).toBe("string");
        expect(typeof category.color).toBe("string");
        expect(typeof category.color_name).toBe("string");
      });
    });

    it("should have valid EvaluationStatusColor values", () => {
      const validColors = Object.values(EvaluationStatusColor);
      defaultOutputCategories.forEach((category) => {
        expect(validColors).toContain(category.color);
      });
    });

    it("should have values that represent numeric scores", () => {
      defaultOutputCategories.forEach((category) => {
        const numericValue = parseFloat(category.value);
        expect(numericValue).toBeGreaterThanOrEqual(0);
        expect(numericValue).toBeLessThanOrEqual(1);
      });
    });

    it("should be ordered by value in descending order", () => {
      const values = defaultOutputCategories.map((cat) =>
        parseFloat(cat.value),
      );
      expect(values).toEqual([1.0, 0.5, 0.0]);
    });
  });
});
