/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import AddTagsContainer from "@/components/AddTagsContainer";
import MaterialIcon from "@/components/MaterialIcon";
import Page from "@/components/Page";
import PageHeader from "@/components/PageHeader";
import { routes } from "@/config/routes";
import { TagRaw } from "@/types";
import { Card, Group, HoverCard, Tabs, Text } from "@mantine/core";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

import APIKeyList from "./components/APIKeyList";
import ModelManager from "./components/ModelManager";
import "./styles/main.scss";

export default function SettingsPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [, setAddedTags] = useState<TagRaw[]>([]);

  // Auto-redirect to apiKeys tab if no tab parameter is present
  useEffect(() => {
    const currentTab = searchParams.get("tab");
    if (!currentTab) {
      router.replace(`${routes.settings}?tab=apiKeys`);
    }
  }, [searchParams, router]);

  return (
    <Page fullHeight>
      <PageHeader title="Settings" />

      <Tabs
        defaultValue={"apiKeys"}
        value={searchParams.get("tab") as string}
        onChange={(value) => router.push(`${routes.settings}?tab=${value}`)}
        classNames={{
          tab: "mx-3 px-0 pb-2 text-secondary",
        }}
      >
        <Tabs.List className="mb-[24px] before:border-transparent">
          <Tabs.Tab value="apiKeys">API Keys</Tabs.Tab>
          <Tabs.Tab value="modelManager">Model manager</Tabs.Tab>
          <Tabs.Tab value="tagManager">Tag manager</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="apiKeys">
          <Card
            className="gap-3xl border-lightSilver rounded-xl border border-solid"
            shadow="md"
          >
            <Text className="!font-medium text-title-22">API Keys</Text>

            <Group
              gap="0"
              className="flex w-[100%] flex-row flex-nowrap items-center"
            >
              <Text className="text-body-12">
                Stax uses your API keys to interact with AI models on your
                behalf. The respective model provider&apos;s terms, data
                policies, and costs will apply, and your data is sent to them.
              </Text>
              <HoverCard
                classNames={{
                  dropdown: "!rounded-lg p-4 shadow-lg",
                }}
              >
                <HoverCard.Target>
                  <Group className="ml-2">
                    <MaterialIcon
                      name="info"
                      className="cursor-pointer text-resting"
                      size={20}
                    />
                  </Group>
                </HoverCard.Target>
                <HoverCard.Dropdown>
                  <Group className="max-w-[330px]">
                    <ul className="list-disc px-[16px]">
                      <li className="my-[4px] text-body-12">
                        Stax lets you test, evaluate, and build effective
                        prompts across various AI models, including third-party
                        models.
                      </li>
                      <li className="my-[4px] text-body-12">
                        You interact with these models via API, using your own
                        API keys.
                      </li>
                      <li className="my-[4px] text-body-12">
                        Your use of APIs via Stax remains subject to applicable
                        terms and privacy policies, and may incur costs.
                      </li>
                      <li className="my-[4px] text-body-12">
                        When you interact with an API via Stax, your data is
                        sent to that third party.
                      </li>
                      <li className="mt-[4px] text-body-12">
                        Google is not responsible for content generated by
                        third-party APIs, or for the use of your data by those
                        third parties.
                      </li>
                    </ul>
                  </Group>
                </HoverCard.Dropdown>
              </HoverCard>
            </Group>

            <Group className="gap-3xl flex w-[100%] flex-col items-start">
              <Group gap={4}>
                <Text className="text-title-16">Model providers</Text>
                <MaterialIcon
                  name="info"
                  className="cursor-pointer text-resting"
                  tooltipClassName="min-w-[200px]"
                  tooltipOffset={8}
                  tooltipPosition="top"
                  tooltipLabel="Add and manage API keys for different model providers. You'll need to generate these keys on their platforms first."
                />
              </Group>
              <APIKeyList />
            </Group>
          </Card>
        </Tabs.Panel>

        <Tabs.Panel value="modelManager">
          <ModelManager />
        </Tabs.Panel>

        <Tabs.Panel value="tagManager">
          <Card
            className="gap-3xl border-lightSilver rounded-xl border border-solid"
            shadow="md"
          >
            <Text className="!font-medium text-title-22">Tag Manager</Text>

            <AddTagsContainer
              searchTagHeaderLabel="Add Tags"
              searchTagHeaderTooltip="Create system tags to be used on models and evaluations. Tags enable filtering and grouping on the analytics page."
              tagsHeaderLabel="All Tags"
              tagsHeaderTooltip="Previously created tags."
              inputPlaceholder="Add a single tag or seperate with a comma"
              showSelectedTags={false}
              canDeleteTags={true}
              setAddedTags={setAddedTags}
            />
          </Card>
        </Tabs.Panel>
      </Tabs>
    </Page>
  );
}
