/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.planck.planck.domain.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
public class ModelTokens {

  @Schema(description = "the input tokens to model", example = "100")
  @JsonProperty("input_tokens")
  private Integer inputTokens;

  @Schema(description = "the output tokens generated by model", example = "100")
  @JsonProperty("output_tokens")
  private Integer outputTokens;

  @Schema(description = "the thinking tokens generated by model", example = "100")
  @JsonProperty("thinking_tokens")
  private Integer thinkingTokens;

  @Schema(description = "the total (input + output) tokens generated by model", example = "200")
  @JsonProperty("total_tokens")
  private Integer totalTokens;

  public ModelTokens(
      Integer turnPromptTokens, Integer turnCompletionTokens, Integer turnTotalTokens) {
    this.inputTokens = turnPromptTokens;
    this.outputTokens = turnCompletionTokens;
    this.totalTokens = turnTotalTokens;
    this.thinkingTokens = turnTotalTokens - (turnPromptTokens + turnCompletionTokens);
  }
}
